export const players = [
  {
    first_name: "Petr",
    last_name: "Bellerin",
    team: "Arsenal",
    position: "Defender",
    image: "images/profile.jpg",
  },
  {
    first_name: "Petr",
    last_name: "Cech",
    team: "Arsenal",
    position: "Goalkeeper",
    image: "images/profile.jpg",
  },
  {
    first_name: "Olivier",
    last_name: "Giroud",
    team: "Arsenal",
    position: "Striker",
    image: "images/profile.jpg",
  },
  {
    first_name: "Alex",
    last_name: "Iwobi",
    team: "Arsenal",
    position: "Midfielder 2",
    image: "images/profile.jpg",
  },
  {
    first_name: "Laurent",
    last_name: "Koscielny",
    team: "Arsenal",
    position: "Defender",
    image: "images/profile.jpg",
  },
  {
    first_name: "Mesut",
    last_name: "Ozil",
    team: "Arsenal",
    position: "Midfielder 1",
    image: "images/profile.jpg",
  },
  {
    first_name: "Alexis",
    last_name: "Sanchez",
    team: "Arsenal",
    position: "Striker",
    image: "images/profile.jpg",
  },
  {
    first_name: "Theo",
    last_name: "Walcott",
    team: "Arsenal",
    position: "Midfielder 2",
    image: "images/profile.jpg",
  },
  {
    first_name: "Marcos",
    last_name: "Alonso",
    team: "Chelsea",
    position: "Defender",
    image: "images/profile.jpg",
  },
];
